//export const PERSON_QUERY_BASE='PERSON_QUERY_BASE';

export const More_isShow='More_isShow';

export const PERSON_QUERY_BASEINFO="PERSON_QUERY_BASEINFO";

export const REVICE_BASEINFO="REVICE_BASEINFO";

export const PERSON_ADDNODE='PERSON_ADDNODE';

export const PERSON_ADDDRAFT='PERSON_ADDDRAFT';

export const PERSON_QUERY_DRAFT='PERSON_QUERY_DRAFT';

export const IS_QUERY_DRAFTIST='IS_QUERY_DRAFTIST';

export const REMOVE_DRAFT='REMOVE_DRAFT';

export const REVISE_DRAFT='REVISE_DRAFT';

export const CHANGEFOCUS='CHANGEFOCUS';

export const GETATTENTIONINFO='GETATTENTIONINFO';

export const UPDATAHOME='UPDATAHOME';

export const ADDLIKE='ADDLIKE';

export const REMOVELIKE='REMOVELIKE';

export const ADDCOLLET='ADDCOLLET';

export const REMOVECOLLET='REMOVECOLLET';

export const QUERY_MYLIKES="QUERY_MYLIKES";

export const QUERY_MYNODE="QUERY_MYNODE";

export const ATTENTIONPERSONLIST="ATTENTIONPERSONLIST";

export const INTERESTINGPERSONLIST="INTERESTINGPERSONLIST";

export const ADDATTENTIONPERSON="ADDATTENTIONPERSON";

export const REMOVEATTENTIONPERSON="REMOVEATTENTIONPERSON";


//ATTENTIONPERSONLIST,INTERESTINGPERSONLIST,ADDATTENTIONPERSON,REMOVEATTENTIONPERSON



export const COURSE_QUERY_BANNER = 'COURSE_QUERY_BANNER';
export const COURSE_QUERY_LIST='COURSE_QUERY_LIST';

export const COURSE_UNPAY='COURSE_UNPAY';
export const COURSE_PAY='COURSE_PAY';
